---
- name: Start Guacamole
  when: guacamole_enabled
  block:
    - name: Check for Guacamole Breaking Changes
      ansible.builtin.include_role:
        name: breaking_changes
      vars:
        breaking_changes_application: guacamole

    - name: Create Guacamole directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ guacamole_data_directory }}/config"

    - name: Guacamole Docker Container
      community.docker.docker_container:
        name: "{{ guacamole_container_name }}"
        image: "{{ guacamole_image_name }}:{{ guacamole_image_version }}"
        pull: true
        volumes:
          - "{{ guacamole_data_directory }}/config:/config:rw"
        ports:
          - "{{ guacamole_port }}:8080"
        restart_policy: unless-stopped
        memory: "{{ guacamole_memory }}"
        labels:
          traefik.enable: "{{ (guacamole_dns_accessible or guacamole_available_externally) | string }}"
          traefik.http.services.guacamole.loadbalancer.server.port: "8080"
          traefik.http.routers.guacamole.rule: "Host(`{{ guacamole_hostname }}.{{ dns_domain }}`)"
          traefik.http.routers.guacamole.tls.domains[0].main: "{{ dns_domain }}"
          traefik.http.routers.guacamole.tls.domains[0].sans: "*.{{ dns_domain }}"
          traefik.http.routers.guacamole.tls.certresolver: "letsencrypt"
          traefik.http.routers.guacamole.middlewares: "{{ omit if guacamole_available_externally else 'blockExternal@file' }}"

- name: Stop Guacamole
  when: not guacamole_enabled
  block:
    - name: Stop Guacamole
      community.docker.docker_container:
        name: "{{ guacamole_container_name }}"
        state: absent
