---
- name: Start Netbootxyz
  when: netbootxyz_enabled
  block:
    - name: Check for Netbootxyz Breaking Changes
      ansible.builtin.include_role:
        name: breaking_changes
      vars:
        breaking_changes_application: netbootxyz

    - name: Netbootxyz Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ netbootxyz_config_directory }}"
        - "{{ netbootxyz_assets_directory }}"

    - name: Netbootxyz Docker Container
      community.docker.docker_container:
        name: "{{ netbootxyz_container_name }}"
        image: "{{ netbootxyz_image_name }}:{{ netbootxyz_image_version }}"
        pull: true
        volumes:
          - "{{ netbootxyz_config_directory }}:/config:rw"
          - "{{ netbootxyz_assets_directory }}:/assets:rw"
        ports:
          - "{{ netbootxyz_web_port }}:3000"
          - "{{ netbootxyz_assets_port }}:80"
          - "{{ netbootxyz_tftp_port }}:69/udp"
        memory: "{{ netbootxyz_memory }}"
        env:
          TZ: "{{ computer_timezone }}"
          PUID: "{{ netbootxyz_user_id }}"
          PGID: "{{ netbootxyz_group_id }}"
        restart_policy: unless-stopped
        labels:
          traefik.enable: "{{ (netbootxyz_dns_accessible or netbootxyz_available_externally) | string }}"
          traefik.http.services.netbootxyz.loadbalancer.server.port: "3000"
          traefik.http.routers.netbootxyz.rule: "Host(`{{ netbootxyz_hostname }}.{{ dns_domain }}`)"
          traefik.http.routers.netbootxyz.tls.domains[0].main: "{{ dns_domain }}"
          traefik.http.routers.netbootxyz.tls.domains[0].sans: "*.{{ dns_domain }}"
          traefik.http.routers.netbootxyz.tls.certresolver: "letsencrypt"
          traefik.http.routers.netbootxyz.middlewares: "{{ omit if netbootxyz_available_externally else 'blockExternal@file' }}"

- name: Stop Netbootxyz
  when: not netbootxyz_enabled
  block:
    - name: Stop Netbootxyz
      community.docker.docker_container:
        name: "{{ netbootxyz_container_name }}"
        state: absent
