---
- name: Start Transmission
  when: transmission_enabled
  block:
    - name: Check for Transmission Breaking Changes
      ansible.builtin.include_role:
        name: breaking_changes
      vars:
        breaking_changes_application: transmission

    - name: Create Transmission Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ transmission_config_directory }}"
        - "{{ transmission_download_directory }}"
        - "{{ transmission_watch_directory }}"

    - name: Transmission Docker Container
      community.docker.docker_container:
        name: "{{ transmission_container_name }}"
        image: "{{ transmission_image_name }}:{{ transmission_image_version }}"
        pull: true
        volumes:
          - "{{ transmission_config_directory }}:/config:rw"
          - "{{ transmission_download_directory }}:/downloads:rw"
          - "{{ transmission_watch_directory }}:/watch:rw"
        ports:
          - "{{ transmission_webui_port }}:9091"
          - "{{ transmission_external_port }}:51413"
          - "{{ transmission_external_port }}:51413/udp"
        env:
          TZ: "{{ computer_timezone }}"
          PUID: "{{ transmission_user_id }}"
          PGID: "{{ transmission_group_id }}"
        restart_policy: unless-stopped
        memory: "{{ transmission_memory }}"
        labels:
          traefik.enable: "{{ (transmission_dns_accessible or transmission_available_externally) | string }}"
          traefik.http.services.transmission.loadbalancer.server.port: "9091"
          traefik.http.routers.transmission.rule: "Host(`{{ transmission_hostname }}.{{ dns_domain }}`)"
          traefik.http.routers.transmission.tls.domains[0].main: "{{ dns_domain }}"
          traefik.http.routers.transmission.tls.domains[0].sans: "*.{{ dns_domain }}"
          traefik.http.routers.transmission.tls.certresolver: "letsencrypt"
          traefik.http.routers.transmission.middlewares: "{{ omit if transmission_available_externally else 'blockExternal@file' }}"

- name: Stop Transmission
  when: not transmission_enabled
  block:
    - name: Stop Transmission
      community.docker.docker_container:
        name: "{{ transmission_container_name }}"
        state: absent
