---
- name: Start Gotify
  when: gotify_enabled
  block:
    - name: Check for Gotify Breaking Changes
      ansible.builtin.include_role:
        name: breaking_changes
      vars:
        breaking_changes_application: gotify

    - name: Create Gotify Data Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ gotify_data_directory }}"

    - name: Gotify Docker Container
      community.docker.docker_container:
        name: "{{ gotify_container_name }}"
        image: "{{ gotify_image_name }}:{{ gotify_image_version }}"
        pull: true
        ports:
          - "{{ gotify_port }}:80"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "{{ gotify_data_directory }}:/app/data:rw"
        env:
          TZ: "{{ computer_timezone }}"
          PUID: "{{ gotify_user_id }}"
          PGID: "{{ gotify_group_id }}"
        restart_policy: unless-stopped
        memory: "{{ gotify_memory }}"
        labels:
          traefik.enable: "{{ (gotify_dns_accessible or gotify_available_externally) | string }}"
          traefik.http.services.gotify.loadbalancer.server.port: "80"
          traefik.http.routers.gotify.rule: "Host(`{{ gotify_hostname }}.{{ dns_domain }}`)"
          traefik.http.routers.gotify.tls.domains[0].main: "{{ dns_domain }}"
          traefik.http.routers.gotify.tls.domains[0].sans: "*.{{ dns_domain }}"
          traefik.http.routers.gotify.tls.certresolver: "letsencrypt"
          traefik.http.routers.gotify.middlewares: "{{ omit if gotify_available_externally else 'blockExternal@file' }}"

- name: Stop Gotify
  when: not gotify_enabled
  block:
    - name: Stop Gotify
      community.docker.docker_container:
        name: "{{ gotify_container_name }}"
        state: absent
