[entryPoints]
  [entryPoints.web]
    address = ":{{ traefik_http_port }}"

  [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"

  [entryPoints.websecure]
    address = ":{{ traefik_https_port }}"

      [entryPoints.websecure.http.tls]
        certResolver = "letsencrypt"

        [entryPoints.websecure.http.tls.domains]
          main = "{{ dns_domain }}"
          sans = [
            "*.{{ dns_domain }}"
          ]

  [entryPoints.traefik]
    address = ":{{ traefik_ui_port }}"

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    exposedbydefault = false

[api]
  insecure = true
  dashboard = true

[log]
  level = "{{ traefik_log_level }}"

[ping]
  terminatingStatusCode = 0

[certificatesResolvers]
  [certificatesResolvers.letsencrypt]
    [certificatesResolvers.letsencrypt.acme]
      email = "{{ dns_email }}"
      storage = "/letsencrypt/acme.json"
      caserver = "{{ traefik_acme_server }}"

      [certificatesResolvers.letsencrypt.acme.dnsChallenge]
        provider = "{{ traefik_dns_provider }}"
        disablePropagationCheck = true
        delayBeforeCheck = "60"

[metrics]
  [metrics.prometheus]

[providers.file]
  directory = "/etc/traefik/"