---

- name: Start Apcupsd
  when: apcupsd_enabled
  block:
    - name: Check for Apcupsd Breaking Changes
      ansible.builtin.include_role:
        name: breaking_changes
      vars:
        breaking_changes_application: apcupsd

    - name: Create Apcupsd Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ apcupsd_data_directory }}"

    - name: Check if Apcupsd config exists
      ansible.builtin.stat:
        path: "{{ apcupsd_data_directory }}/apcupsd.conf"
      register: apcupsd_config_path

    - name: Template Apcupsd config
      ansible.builtin.template:
        src: apcupsd.conf
        dest: "{{ apcupsd_data_directory }}/apcupsd.conf"
      when: not apcupsd_config_path.stat.exists

    - name: Apcupsd Docker Container
      community.docker.docker_container:
        name: "{{ apcupsd_container_name }}"
        image: "{{ apcupsd_image_name }}:{{ apcupsd_image_version }}"
        pull: true
        privileged: true
        volumes:
          - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"
          - "{{ apcupsd_data_directory }}/apcupsd.conf:/etc/apcupsd/apcupsd.conf"
        ports:
          - "{{ apcupsd_port }}:3551"
        devices:
          - "{{ apcupsd_device }}:{{ apcupsd_device }}"
        env:
          TZ: "{{ computer_timezone }}"
        restart_policy: unless-stopped
        memory: "{{ apcupsd_memory }}"

- name: Stop Apcupsd
  when: not apcupsd_enabled
  block:
    - name: Stop Apcupsd
      community.docker.docker_container:
        name: "{{ apcupsd_container_name }}"
        state: absent
